# Generated by Django 5.0.14 on 2026-09-26 16:39

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('connections', '0001_initial'),
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QueryHistoryItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('natural_query', models.TextField()),
                ('generated_sql', models.TextField()),
                ('status', models.CharField(choices=[('success', 'Success'), ('error', 'Error'), ('clarified', 'Clarified')], default='success', max_length=20)),
                ('execution_time_ms', models.FloatField(default=0.0)),
                ('row_count', models.IntegerField(default=0)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('clarification_log', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('connection', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='queries', to='connections.databaseconnection')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='query_history', to='organizations.organization')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='queries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'query_history',
                'ordering': ['-created_at'],
            },
        ),
    ]
