# Generated by Django 5.0.14 on 2026-09-26 16:39

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('connections', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchemaMetadata',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('raw_schema', models.JSONField(default=dict)),
                ('table_count', models.IntegerField(default=0)),
                ('synced_at', models.DateTimeField(auto_now=True)),
                ('connection', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='schema_metadata', to='connections.databaseconnection')),
            ],
            options={
                'db_table': 'schema_metadata',
            },
        ),
    ]
