# Generated by Django 5.0.14 on 2026-09-26 16:39

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DatabaseConnection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('db_type', models.CharField(choices=[('sqlite', 'SQLite'), ('postgresql', 'PostgreSQL'), ('mysql', 'MySQL')], max_length=20)),
                ('host', models.CharField(blank=True, default='localhost', max_length=255)),
                ('port', models.IntegerField(default=5432)),
                ('database_name', models.CharField(max_length=255)),
                ('username', models.CharField(blank=True, default='', max_length=100)),
                ('encrypted_password', models.TextField(blank=True, default='')),
                ('ssl_enabled', models.BooleanField(default=False)),
                ('schema_cache', models.JSONField(blank=True, null=True)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connections', to='organizations.organization')),
            ],
            options={
                'db_table': 'database_connections',
                'ordering': ['-created_at'],
            },
        ),
    ]
